{
    "en": [{
        "close": "Close",
        "loading": "Loading...",
        "elementsTab": "Elements",
        "propertyTab": "Property",
        "blankPage": "Blank Page",
        "collapseMenu": "Collapse Menu",
        "settingsPreview": "Preview",
        "settingsExport": "Export",
        "settingsImport":"Import",
        "settingsSaveTemplate": "Save Template",
        "settingsLoadTemplate": "Load Template",
        "settingsSendMail": "Send Mail",
        "propertyBG": "Background",
        "propertyPadding": "Padding",
        "propertyBorderRadius": "Border Radius",
        "propertyTextStyle": "Text Style",
        "propertySocialContent": "Social content",
        "propertyEmailWidth": "Email Width",
        "propertyEmailWidthHelp": "email width must be 300-1000px",
        "propertyImageSettings": "Image settings",
        "propertyChangeImage": "Change image",
        "propertyHyperlink": "Hyperlink",

        "popupImageTitle": "Select image",
        "popupImageUpload": "Upload",
        "popupImageOk": "Select",
        "popupImageClose": "Close",
        "popupSaveTemplateTitle": "Save template",
        "popupSaveTemplateSubTitle": "Please write template name",
        "popupSaveTemplatePLaceHolder": "Please enter template name",
        "popupSaveTemplateError": "Template name required",
        "popupSaveTemplateOk": "Save",
        "popupSaveTemplateClose": "Close",
        "popupEditorTitle": "Edit Source",
        "popupEditorOk": "Save",
        "popupEditorClose": "Close",
        "popupSendEmailTitle": "Send Email",
        "popupSendEmailSubTitle": "Please write email address",
        "popupSendEmailPlaceHolder": "Please enter your email address",
        "popupSendEmailTitle": "Please enter your email subject",
        "popupSendEmailOk": "Send Email",
        "popupSendEmailClose": "Close",
        "popupLoadTemplateTitle": "Load template",
        "popupLoadTemplateSubtitle": "Please select template for load",
        "popupLoadTemplateOk": "Load",
        "popupLoadTemplateClose": "Close",

        "propertyButton": "Button",
        "modalDeleteTitle": "Are you sure ?",
        "modalDeleteconfirmButtonText": "Yes",
        "modalDeleteText": "You won't be able to revert this!",
        "modalDeletecancelButtonText": "No",
        "commandUndo": "Undo",
        "commandRedo": "Redo",



        "setttingsMobileViewTitle": "Other devices",
        "setttingsMobileViewMobileDesc": "Mobile content",
        "setttingsMobileViewDesktopDesc": "Desktop content",
        "popupImportTitle":"Select file for the import",
        "popupImportUpload":"Import template"
    }],
    "fr": [{
        "close": "Fermer",
        "loading": "Chargement...",
        "elementsTab": "Éléments",
        "propertyTab": "Propriété",

        "blankPage": "Page blanche",
        "collapseMenu": "Réduire Menu",
        "settingsPreview": "Aperçu",
        "settingsExport": "Exportation",
        "settingsSaveTemplate": "Enregistrer le modèle",
        "settingsLoadTemplate": "Modèle de charge",
        "settingsSendMail": "Envoyer un mail",
        "propertyBG": "Background",
        "propertyPadding": "Padding",
        "propertyBorderRadius": "Border Radius",
        "propertyTextStyle": "Text Style",
        "propertySocialContent": "Social content",
        "propertyEmailWidth": "Email Width",
        "propertyEmailWidthHelp": "largeur de courriel doit être 300-1000px",
        "propertyImageSettings": "Image settings",
        "propertyChangeImage": "Changer l'image",
        "propertyHyperlink": "Hyperlink",
        "propertyButton": "Button",
        "popupImageTitle": "Sélectionner une image",
        "popupImageUpload": "Télécharger",
        "popupImageOk": "Sélectionner",
        "popupImageClose": "Fermer",
        "popupSaveTemplateTitle": "Enregistrer le modèle",
        "popupSaveTemplateSubTitle": "S'il vous plaît écrire le nom modèle",
        "popupSaveTemplatePLaceHolder": "S'il vous plaît entrez le nom modèle",
        "popupSaveTemplateError": "Nom du modèle requis",
        "popupSaveTemplateOk": "Sauvegarder",
        "popupSaveTemplateClose": "Fermer",
        "popupEditorTitle": "Modifier la source",
        "popupEditorOk": "Sauvegarder",
        "popupEditorClose": "Fermer",
        "popupSendEmailTitle": "Envoyer un mail",
        "popupSendEmailSubTitle": "S'il vous plaît écrivez adresse e-mail",
        "popupSendEmailPlaceHolder": "S'il vous plaît entrer votre adresse e-mail",
        "popupSendEmailOk": "Envoyer un mail",
        "popupSendEmailClose": "Fermer",
        "popupLoadTemplateTitle": "Charger modèle",
        "popupLoadTemplateSubtitle": "Please select template for load",
        "popupLoadTemplateOk": "Charge",
        "popupLoadTemplateClose": "Fermer",

        "modalDeleteTitle": "Are you sure ?",
        "modalDeleteText": "You won't be able to revert this!",
        "modalDeleteconfirmButtonText": "Yes",
        "modalDeletecancelButtonText": "No"
    }],
    "it": [{
        "close": "Vicino",
        "loading": "Caricamento in corso...",
        "elementsTab": "Elementi",
        "propertyTab": "Proprietà",
        "blankPage": "Pagina vuota",
        "collapseMenu": "Collapse Menu",
        "settingsPreview": "Anteprima",
        "settingsExport": "Esportare",
        "settingsSaveTemplate": "Salva modello",
        "settingsLoadTemplate": "Carica modello",
        "settingsSendMail": "Inviare una mail",
        "propertyBG": "Background",
        "propertyPadding": "Padding",
        "propertyBorderRadius": "Border Radius",
        "propertyTextStyle": "Text Style",
        "propertySocialContent": "Social content",
        "propertyEmailWidth": "Email Width",
        "propertyEmailWidthHelp": "larghezza e-mail deve essere 300-1000px",
        "propertyImageSettings": "Image settings",
        "propertyChangeImage": "Cambia immagine",
        "propertyHyperlink": "Hyperlink",
        "propertyButton": "Button",
        "popupImageTitle": "Seleziona immagine",
        "popupImageUpload": "Caricare",
        "popupImageOk": "Selezionare",
        "popupImageClose": "Vicino",
        "popupSaveTemplateTitle": "Salva modello",
        "popupSaveTemplateSubTitle": "Si prega di scrivere il nome del modello",
        "popupSaveTemplatePLaceHolder": "Si prega di inserire il nome del modello",
        "popupSaveTemplateError": "Nome del modello richiesto",
        "popupSaveTemplateOk": "Salvare",
        "popupSaveTemplateClose": "Vicino",
        "popupEditorTitle": "Modifica origine",
        "popupEditorOk": "Salvare",
        "popupEditorClose": "Vicino",
        "popupSendEmailTitle": "Invia una email",
        "popupSendEmailSubTitle": "Si prega di scrivere e-mail",
        "popupSendEmailPlaceHolder": "Inserisci il tuo indirizzo email",
        "popupSendEmailOk": "Invia una email",
        "popupSendEmailClose": "Vicino",
        "popupLoadTemplateTitle": "Carica modello",
        "popupLoadTemplateSubtitle": "Seleziona modello per carico",
        "popupLoadTemplateOk": "Caricare",
        "popupLoadTemplateClose": "Vicino",

        "modalDeleteTitle": "Are you sure ?",
        "modalDeleteText": "You won't be able to revert this!",
        "modalDeleteconfirmButtonText": "Yes",
        "modalDeletecancelButtonText": "No"
    }],
    "tr": [{
        "close": "Kapat",
        "loading": "Yükleniyor...",
        "elementsTab": "Öğe",
        "propertyTab": "Özellik",
        "blankPage": "Boş sayfa",
        "collapseMenu": "Menunu kapat",
        "settingsPreview": "Önizleme",
        "settingsExport": "İhracat",
        "settingsSaveTemplate": "Şablonu Kaydet",
        "settingsLoadTemplate": "Şablonu yükle",
        "settingsSendMail": "Posta gönder",
        "propertyBG": "Background",
        "propertyButton": "Button",
        "propertyPadding": "Padding",
        "propertyBorderRadius": "Border Radius",
        "propertyTextStyle": "Text Style",
        "propertySocialContent": "Social content",
        "propertyEmailWidth": "Email Width",
        "propertyEmailWidthHelp": "E-posta genişliği 300-1000px olmalıdır",
        "propertyImageSettings": "Image settings",
        "propertyChangeImage": "Change image",
        "propertyHyperlink": "Hyperlink",
        "popupImageTitle": "Görüntü seç",
        "popupImageUpload": "Yükle",
        "popupImageOk": "Seçmek",
        "popupImageClose": "Kapat",
        "popupSaveTemplateTitle": "Şablonu kaydet",
        "popupSaveTemplateSubTitle": "Şablon adını yazınız",
        "popupSaveTemplatePLaceHolder": "Şablon adı girin",
        "popupSaveTemplateError": "Şablon adı gerekiyor",
        "popupSaveTemplateOk": "Kayıt",
        "popupSaveTemplateClose": "Kapat",
        "popupEditorTitle": "Kaynağı düzenle",
        "popupEditorOk": "Kayıt",
        "popupEditorClose": "Kapat",
        "popupSendEmailTitle": "E-posta gönder",
        "popupSendEmailSubTitle": "E-posta adresinizi yazınız",
        "popupSendEmailPlaceHolder": "Lütfen e-mail adresinizi giriniz",
        "popupSendEmailOk": "E-posta gönder",
        "popupSendEmailClose": "Kapat",
        "popupLoadTemplateTitle": "Şablon yükle",
        "popupLoadTemplateSubtitle": "Yüklemek için şablon seçiniz",
        "popupLoadTemplateOk": "Yükle",
        "popupLoadTemplateClose": "Kapat",

        "modalDeleteTitle": "Are you sure ?",
        "modalDeleteText": "You won't be able to revert this!",
        "modalDeleteconfirmButtonText": "Yes",
        "modalDeletecancelButtonText": "No"
    }],
    "ru": [{
        "close": "Закрыть",
        "loading": "Загрузка...",
        "elementsTab": "Элементы",
        "propertyTab": "Свойстова",
        "blankPage": "Пустая страница",
        "collapseMenu": "Закрыть Меню",
        "settingsPreview": "Просмотр",
        "settingsExport": "Экспорт",
        "settingsSaveTemplate": "Сохранить шаблон",
        "settingsLoadTemplate": "Шаблон загрузки",
        "settingsSendMail": "Отправить",
        "propertyBG": "Background",
        "propertyButton": "Button",
        "propertyPadding": "Padding",
        "propertyBorderRadius": "Border Radius",
        "propertyTextStyle": "Text Style",
        "propertySocialContent": "Social content",
        "propertyEmailWidth": "Email Width",
        "propertyEmailWidthHelp": "ширина электронной почты должна быть 300-1000px",
        "propertyImageSettings": "Image settings",
        "propertyChangeImage": "Change image",
        "propertyHyperlink": "Hyperlink",
        "popupImageTitle": "Выбрать изображение",
        "popupImageUpload": "Загрузить",
        "popupImageOk": "Выбрать",
        "popupImageClose": "Закрыть",
        "popupSaveTemplateTitle": "Сохранить шаблон",
        "popupSaveTemplateSubTitle": "Пожалуйста, напишите имя шаблона",
        "popupSaveTemplatePLaceHolder": "Пожалуйста, введите имя шаблона",
        "popupSaveTemplateError": "Имя шаблона требуется",
        "popupSaveTemplateOk": "Сохранить",
        "popupSaveTemplateClose": "Закрыть",
        "popupEditorTitle": "Изменить источник",
        "popupEditorOk": "Сохранить",
        "popupEditorClose": "Закрыть",
        "popupSendEmailTitle": "Отправить на e-mail",
        "popupSendEmailSubTitle": "Пожалуйста, напишите адрес электронной почты",
        "popupSendEmailPlaceHolder": "Пожалуйста, введите Ваш адрес электронной почты",
        "popupSendEmailOk": "Отправить на e-mail",
        "popupSendEmailClose": "Закрыть",
        "popupLoadTemplateTitle": "Шаблон загрузки",
        "popupLoadTemplateSubtitle": "Пожалуйста, выберите шаблон для загрузки",
        "popupLoadTemplateOk": "Загрузка",
        "popupLoadTemplateClose": "Закрыть",

        "modalDeleteTitle": "Are you sure ?",
        "modalDeleteText": "You won't be able to revert this!",
        "modalDeleteconfirmButtonText": "Yes",
        "modalDeletecancelButtonText": "No"

    }],
    "es": [{
        "close": "Cerrar",
        "loading": "Cargando...",
        "elementsTab": "Elementos",
        "propertyTab": "Propiedades",
        "blankPage": "Página en blanco",
        "collapseMenu": "Ocultar menú",
        "settingsPreview": "Vista previa",
        "settingsExport": "Exportar",
        "settingsSaveTemplate": "Guardar boletín",
        "settingsLoadTemplate": "Cargar boletín",
        "settingsSendMail": "Enviar boletín",
        "propertyBG": "Fondo",
        "propertyPadding": "Padding",
        "propertyBorderRadius": "Redondeado de bordes",
        "propertyTextStyle": "Estilo del texto",
        "propertySocialContent": "Redes sociales",
        "propertyEmailWidth": "Ancho del correo",
        "propertyEmailWidthHelp": "El ancho del correo debe estar entre 300 y 1000px",
        "propertyImageSettings": "Opciones de imagen",
        "propertyChangeImage": "Cambiar imagen",
        "propertyHyperlink": "Hipervínculo",
        "popupImageTitle": "Seleccionar una imagen",
        "popupImageUpload": "Subir",
        "popupImageOk": "Seleccionar",
        "popupImageClose": "Cerrar",
        "popupSaveTemplateTitle": "Guardar boletín",
        "popupSaveTemplateSubTitle": "Por favor escriba un nombre para el boletín",
        "popupSaveTemplatePLaceHolder": "Por favor ingrese un nombre para el boletín",
        "popupSaveTemplateError": "El nombre del boletín es requerido",
        "popupSaveTemplateOk": "Guardar",
        "popupSaveTemplateClose": "Cerrar",
        "popupEditorTitle": "Editar fuente",
        "popupEditorOk": "Guardar",
        "popupEditorClose": "Cerrar",
        "popupSendEmailTitle": "Enviar boletín",
        "popupSendEmailSubTitle": "Por favor escriba una dirección de correo electrónico",
        "popupSendEmailPlaceHolder": "Por favor ingrese una dirección de correo electrónico",
        "popupSendEmailOk": "Enviar boletín",
        "popupSendEmailClose": "Cerrar",
        "popupLoadTemplateTitle": "Abrir boletín",
        "popupLoadTemplateSubtitle": "Por favor selecciona un boletín para abrir",
        "popupLoadTemplateOk": "Abrir",
        "popupLoadTemplateClose": "Cerrar"
    }],
    "de": [{
        "close": "Schließen",
        "loading": "Laden...",
        "elementsTab": "Elemente",
        "propertyTab": "Eigentum",
        "blankPage": "Leere Seite",
        "collapseMenu": "Menü reduzieren",
        "settingsPreview": "Vorschau",
        "settingsExport": "Export",
        "settingsSaveTemplate": "Vorlage speichern",
        "settingsLoadTemplate": "Vorlage laden",
        "settingsSendMail": "Mail senden",
        "propertyBG": "Background",
        "propertyPadding": "Padding",
        "propertyBorderRadius": "Border Radius",
        "propertyTextStyle": "Text Style",
        "propertyButton": "Button",
        "propertySocialContent": "Social content",
        "propertyEmailWidth": "Email Width",
        "propertyEmailWidthHelp": "E-Mail-Breite muss 300-1000px betragen",
        "propertyImageSettings": "Image settings",
        "propertyChangeImage": "Change image",
        "propertyHyperlink": "Hyperlink",
        "popupImageTitle": "Bild auswählen",
        "popupImageUpload": "Hochladen",
        "popupImageOk": "Wählen",
        "popupImageClose": "Schließen",
        "popupSaveTemplateTitle": "Vorlage speichern",
        "popupSaveTemplateSubTitle": "Bitte Name der Vorlage eingeben",
        "popupSaveTemplatePLaceHolder": "Bitte geben Sie einen Vorlagennamen ein",
        "popupSaveTemplateError": "Name der Vorlage erforderlich",
        "popupSaveTemplateOk": "Sparen",
        "popupSaveTemplateClose": "Schließen",
        "popupEditorTitle": "Quelle bearbeiten",
        "popupEditorOk": "Sparen",
        "popupEditorClose": "Schließen",
        "popupSendEmailTitle": "E-Mail senden",
        "popupSendEmailSubTitle": "Bitte schreiben Sie eine E-Mail-Adresse",
        "popupSendEmailPlaceHolder": "Geben Sie bitte Ihre Email-Adresse ein",
        "popupSendEmailOk": "E-Mail senden",
        "popupSendEmailClose": "Schließen",
        "popupLoadTemplateTitle": "Ladeschablone",
        "popupLoadTemplateSubtitle": "Bitte wählen Sie eine Vorlage für die Beladung",
        "popupLoadTemplateOk": "Belastung",
        "popupLoadTemplateClose": "Schließen",

        "modalDeleteTitle": "Are you sure ?",
        "modalDeleteText": "You won't be able to revert this!",
        "modalDeleteconfirmButtonText": "Yes",
        "modalDeletecancelButtonText": "No"
    }]
}
